### PR TITLE
Add Korean translation

### PR DESCRIPTION
**Pull request by ericswpark**
(please let me know if I missed any other files that need to be translated!)

### CODE REVIEW

**Review by lxndrblz — APPROVED** [review]
Thanks for adding Korean.

**Comment by ericswpark** [comment]
@lxndrblz Sorry, I think I committed too fast. Currently the Korean translations are broken:

    WARN 2021/03/27 21:53:49 Failed to get translated string for language "art-x-kr" and ID "page_not_found": %!s(<nil>)
    WARN 2021/03/27 21:53:49 Failed to get translated string for language "art-x-kr" and ID "page_does_not_exist": %!s(<nil>)
    WARN 2021/03/27 21:53:49 Failed to get translated string for language "art-x-kr" and ID "head_back": %!s(<nil>)

This is possibly an upstream bug: https://github.com/gohugoio/hugo/issues/7838

**Comment by ericswpark** [comment]
Confirmed it's not a problem with my translation. It happens even if I simply copy `en.toml` to `kr.toml`. Most likely some sort of upstream bug. The linked bugreport says it wasn't a problem in previous Hugo versions.

**Comment by lxndrblz** [comment]
@ericswpark I just realised it has to be called ko.toml. Using a fairly reason Hugo version (v.0.80) I didn't have any issues.

**Comment by ericswpark** [comment]
@lxndrblz ahh, thank you so much! Sorry for the mistake. I assumed Go used kr for Korean because it accepted the Languages.kr configurations for my blog. Can confirm on my end ko works without problems.

**Pull request merged**
