### PR TITLE
add light/dark mode switcher.

### PR DESCRIPTION
**Pull request by bkanhu**
Created a light/dark mode switcher. and add CSS variables to reduce time while changing the color of the webpage.

### CODE REVIEW

**Comment by lxndrblz** [comment]
Hello Kanhu, Thanks for your contribution. It's well appreciated. 👍 

The approach that you've chosen is very similar to how I wanted to realize it anyways.
I'll thoroughly review it and if nothing breaks I'll go ahead and merge it.

One thing that might be a bit iffy is the inline JS code, as this doesn't work with strict CSPs. I'll check if we could either move it to a separate file that could be fingerprinted and processed through hugo pipes.

**Comment by bkanhu** [comment]
Hello Alexander, Thanks. I thought to make a separate file but ended up writing in-line.

**Comment by lxndrblz** [comment]
Hello Kanhu,

Thanks again for your pull request. I've made some changes in order to make the dark theme a bit more consistent with the overall theme. Please let me know what you think.

Something I am not quite satisfied with is the colour choice of the texts in the sidebar, as they are very hard to read.

**Comment by bkanhu** [comment]
Thanks, Alexander, 
That's totally ok. I also just realized the text color. You did a good job of putting in-line JS to a separate file. 
But please make the toggler a bit larger so that it'll noticeable.

**Comment by lxndrblz** [comment]
Thanks for the latest update! Let's focus on getting the readability improved and then I see no objectives of merging this into the master. 💯

**Pull request merged**
