### PR TITLE
RTL support 

### PR DESCRIPTION
**Pull request by a0m0rajab**
Hey There, 

I just added RTL support for the theme and had some minor changes. The changes is like the next: 

- **RTL support**: By adding the Dir of the HTML file and related CSS file which flipped the theme. 
-  **Fixing i18n:** there was few missed values for the translation that I have added. 
- **Contact Form:** Added the whole contact form value to i18n files. 
- **Example site:** created an example site for Arabic content and refactored the config files.

### CODE REVIEW

**Comment by a0m0rajab** [comment]
Just to mention this would fix #135 issue!

**Comment by lxndrblz** [comment]
@a0m0rajab Thanks for your PR. I went over everything looks good. One minor problem is that the CSS has now some code duplication. I hope to get that resolved when I find some time to finally change the project to SCSS/SASS. Using mixins the code reuse could be addressed fairly easily.

**Comment by a0m0rajab** [comment]
@lxndrblz You are right, I have made two CSS files for that one is RTL the other is the basic, found it as fast-dirty solution to this issue, otherwise it will need to have classes added to the whole code which is more time consuming.

**Comment by lxndrblz** [comment]
@a0m0rajab Feel free to open a new PR, if you want to making it a bit more slick using classes. 👍

**Pull request merged**
