### PR TITLE
Improved wide screen consistency, with easy parametrization.

### PR DESCRIPTION
**Pull request by ivangjxyz**
Just made a couple of changes so that now with wider than `1920px` windows you get a more consistent experience. 

I have made it so that it is very easy to personalize, with two main parameters: 
- `--body-max-width`: the maximum width in `px` for the content of the websites. This should also be used in the `@media` query, only **it has to be put manually there**. Maybe there is a Hugo thing to modify CSS files with external parameters? That could solve the problem. 
- `--content-ratio`: decimal value between `0` and `1` that marks the ratio of the content in respect to the whole width of the website (content+sidebar). 

So, now, you should be able to see that for screens smaller than `--body-max-width` wide you get your page divided by the ratio, and if it's bigger than that... well, now margins are automatically generated and the view stays consistent, while keeping the `--content-ratio`. 

Want to "fall back" to the old "just fill the whole page" thing? Well, setup `--body-max-width` to a stupidly large value, as well as the `@media` query.

### CODE REVIEW

**Comment by ivangjxyz** [comment]
This took me quite a bit more trial and error than I expected, :sweat_smile:, I hope it's fine!

**Comment by lxndrblz** [comment]
@ivangjxyz  Thanks for the PR. I'll check it out and report back. Might take me a day or two.

**Comment by lxndrblz** [comment]
@ivangjxyz  Thanks for your PR. I wanted to give a little update. Technically I couldn't spot any errors. Indeed, I really like the ability to control the ratio! The only reason I haven't merged it yet, is that I am still looking for a slick way on how we could control the variables using the parameters in the conf file.

**Comment by ivangjxyz** [comment]
That would be ideal, specially for the `@media` thingie. Would make things much easier.

**Comment by lxndrblz** [comment]
One way which would work for sure is by using SCSS , template variables and Hugo pipes. I am currently in the process to evaluate how much effort should a refactoring would make. :)

**Comment by lxndrblz** [comment]
I think we could make the transition to SCSS in steps. I've made some first tests and it looks really promising. I'll push an update as soon as I am a bit less busy with university.

**Comment by lxndrblz** [comment]
@ivangjxyz  I've played around with SCSS and was able to control the variables from the config.toml.

Simply set these as following:

```
[params]
body_max_width = "1920px"
content_ratio = 0.7
```

What do you think?

I still need to convert the rest of the CSS and split the variables and different sections in smaller pieces. But overall I really like the abilities of SCSS.

**Comment by ivangjxyz** [comment]
Okay, so I also implemented this little thing with the date format being now more accessible. With the v0.4, the doNotLoadAnimations parameter and everything... it reminded me that I had to use custom .html's particularly just to change date formats. 

I was going to make these changes like the animation one... so that nobody had to touch their config.toml to manually add them... but then I realised that we cannot keep adding and adding `if else` for every other change there is... and I consider the date formats very crucial for anyone to consciously setup, specially considering that **date formats do vary almost person to person**; just consider the different languages... and then there's the more traditional people vs ISO 8601 freaks (me).

**Comment by lxndrblz** [comment]
@ivangjxyz That's a very interesting and at the same time controversial point, which you are bringing up here. 
I know most other theme would just leave everything hard coded, hoping that people just clone the theme. This has the benefit, that any change doesn't have to consider previous versions/leaves the updates to the user. In the past, I preferred the opposite way in the hope, that the theme would be easier to use for beginners. However, I also noticed, that all of the variables can become too overwhelming. 

Back to your date formatting topic. Something I'd been thinking, is whether we could include the date formats in the i18n files. As far as I am aware, dates seem to be language specific. This would have the benefit, that most users would "automatically" get the matching format. Though, I haven't tried it yet.

**Comment by ivangjxyz** [comment]
I do understand your point, I think focusing on easy access for begginers is a great point of view. 

But... I also believe strongly that allowing this easy access to the dateFormat *helps* these begginers, so that they have something that corresponds to their views. It is not just a "visual gimmick", this is about the **actual content**, in my friendly opinion. Some people want to show that this post was made "this day", but not at what hour, etc. Or maybe they just have a "monthly post" or something, and they don't want to relate it to a particular hour. 

The only way I see doing the i18n thing is by *actually implementing this concept*, and making it optional to have these *custom date* parameters in the config.toml. Because if a person wants a specific date format, they'd have to go to every single language in the world and fix that, so we should give them an easy way to override it, for the reasons I express in the previous paragraph. 

Maybe I'll try something like this this weekend... we'll see.

**Comment by lxndrblz** [comment]
@ivangjxyz Good points. It might be best to go the route, which you'd initially suggested (give everyone the ability to control their date formats). I will hopefully find some time over the weekend to continue working on the SCSS changes and playing around with the custom date. Thanks for bringing this to my attention and for the PR.

**Comment by ivangjxyz** [comment]
Now there's backwards compatibility, and the structure is easier for a future i18n thingie addition.

**Comment by lxndrblz** [comment]
@ivangjxyz  Sorry for the late reply. Would you mind moving the date related changes to a separate PR, so we can keep this one focused on the SCSS/display ratio and I can go ahead and merge them?

**Comment by cdichiara** [comment]
Hi folks ... so how would ... I be able to add a commit to this pull request? I would think ... @ivangjxyz would have to give me access to his fork?

Anyways @ivangjxyz I was making some custom css samples, which is asking for hugo template processing to be applied to the custom css and js. I made some changes to `head.html` to allow that to happen ... plus provided a google font example. The changes to `head.html` are in here:

[googleFonts.zip](https://github.com/lxndrblz/anatole/files/5824905/googleFonts.zip)

As is the custom css file. I'm going to make another custom css that involves the profile pic and the mask ... I'll also post it here. I think @lxndrblz wants to combine this work into what you guys are doing here... so let me know how I can be helpful.

Oh here is the summary of the changes to `head.html`, so you don't have to repeat the learning I did:
Line 28:
```
{{ $styles := $minstyles | resources.ExecuteAsTemplate . $ | resources.Minify | resources.Fingerprint }}
```
Line 76:
```
{{- $customJS := resources.Get . | resources.ExecuteAsTemplate "." $ -}}
```

**Comment by cdichiara** [comment]
Ok well @lxndrblz here's one very simple custom css, if you want to use it ... I gave up on the mask because I couldn't it to scale proportionally so I just gave an example of how to round the image a little differently.

Also a slight fix to the Google font one I provided, this time without the head.html.

[googleFonts.zip](https://github.com/lxndrblz/anatole/files/5825158/googleFonts.zip)
[profilePicRounded.zip](https://github.com/lxndrblz/anatole/files/5825159/profilePicRounded.zip)

OK I think those should be good custom css examples...

Carmine

ps. I'm thinking this would be a good time to tweak this:

```css
.sidebar .logo-title {
    text-align: center;
    padding-top: 240px;
    flex: 1;
}
```
This is what it looks like on 2560x1440 at no magnification of the browser:
Screenshot 2021-01-16 16 37 35

The padding-top is just a little too rigid IMO ... if we want it to land at the bottom of the screen there must be a way to be more responsive. Because you can see what happens when you put in a photo with completely reasonable proportions:
Screenshot 2021-01-16 16 44 40

I'm not sure how hard this is, but I'm happy to take a swing at it.

**Comment by lxndrblz** [comment]
@ivangjxyz @cdichiara I've created a seperate branch for the changes related to SCSS where we could all work together. Feel free to make any future PRs to three. For now I've integrated the sidebar ratio, but I still need to split up the files a bit more and make use of the SCSS specialities. In favor of the new branch, I will close this PR.

**Pull request closed without merging**
