### PR TITLE
Thumbnail in post header

### PR DESCRIPTION
**Pull request by LucasVadilho**
While modifying the theme for myself I added support for thumbnail in the post header. Looking at #66 and #59, I see that there's some demand for it.

It is a little different than the screenshot, but I tried to make it fit my version of the theme. I don't know if the way I stylized is what you envisioned. Feel free to disregard this PR if you don't think it fits the theme.

To add the thumbnail all you need to do is add `thumbnail` with the source in the content front-matter. There's also two css variables to control the size and position of the thumbnail.

This is also my first PR so let me know if I did anything wrong.

### CODE REVIEW

**Comment by lxndrblz** [comment]
@LucasVadilho Thanks for your PR. I'll have a look.

**Comment by LucasVadilho** [comment]
> Somethings I've noticed is that it's not optimized for mobile, as the image doesn't wrap below the text.

True, I forgot to add the media rules. In my version I hide the thumbnail.

But it is easy enough to get the thumbnail to wrap below the text.



It's also possible to place it on top of the text, like this:

**Comment by lxndrblz** [comment]
@LucasVadilho Thanks for your contributions. I was also fiddling around for a bit and what I liked best is a simple rectangular post header. What do you think about such an approach?

image

My reasoning for doing it this way is that there is more space to display something meaningful and it looks a bit slicker. 

Please let me know what you think!

**Comment by LucasVadilho** [comment]
@lxndrblz I think it looks great!

Specially with high aspect ratio images. I did some tests with square and lower aspect ratio images and maybe it needs a bit of fine tuning, or the recommendation to use high aspect ratio images.

Screenshot from 2020-09-18 11-07-11

**Comment by lxndrblz** [comment]
@LucasVadilho yes, it does need a bit more fine tuning, I wanted to get the layout right first. 😅 

The problem with squared images is that we'd need to zoom/crop them to make them fit into a rectangular shape, otherwise the posts get very long. Stretching slightly too small images on the other hand shouldn't be that much of an issue.

**Comment by LucasVadilho** [comment]
I've updated the thumbnail container to a fixed height (which can be variable depending on device width) and made it so that the image covers the container, this way the image is cropped or extended while maintaining it's aspect ratio.

**Comment by lxndrblz** [comment]
@LucasVadilho I've updated the design a bit more. Let me know what you think.

Desktop:

image

Mobile:

image

**Comment by LucasVadilho** [comment]
Looks great to me!

**Comment by lxndrblz** [comment]
There are still a couple of things which I need to fix, liked the loading of a local image rather than a random via url.

**Pull request merged**
