### PR TITLE
Adding spanish translation.

### PR DESCRIPTION
**Pull request by ErickCastellanos**

### CODE REVIEW

**Review by ivangjxyz — APPROVED** [review]
Good!

**Comment by lxndrblz** [comment]
@ErickCastellanos  Thanks for your contribution. I'll go ahead and merge it.

**Comment by ErickCastellanos** [comment]
Glad to help! I did it in the spirit of Hacktoberfest. So, if you find my contribution useful, could you please tag my PR with the "hacktoberfest-accepted" label? It will make it appear in my Hacktober contributions. Thanks!

**Comment by lxndrblz** [comment]
@ErickCastellanos No problem, just added your tag.

**Pull request merged**
