### PR TITLE
Added Github Comments

### PR DESCRIPTION
**Pull request by rkbright**
Hi Alex - great theme BTW! I was considering using your theme to migrate my Jekyll content but noticed your theme was limited to Disqus comments. I have GitHub Issues integrated with my Jekyll site (richardbright.me) and wanted to see if I could get it working on your site as an option for future users of your theme. Please have a look and consider merging the changes, it will give folks an alternative option to using Disqus. 

Happy blogging!

### CODE REVIEW

**Comment by lxndrblz** [comment]
@rkbright Hi Richard, thanks for your contribution and great idea!

I'll have to test it a bit more, but overally it looks good. The only thing I noticed is that the url are hardcoded in the JavaScript, which makes it hard for some users to change. Maybe that could be changed.

As always, it would be nice to have a few lines of documentation how it works, but I can also do that myself.

**Comment by rkbright** [comment]
Yeah, we can definitely substitute with a variable that reads from the config.toml file. I can work on some documentation as well, just let me know so I do not duplicate effort.

**Comment by rkbright** [comment]
Okay, give this a try, worked great from my forked copy (https://github.com/rkbright/anatole). Basically, users can set the repo parameter from the ``config.toml`` file or from front matter, depending on how they want to setup the comments. I typically use the same repo for all my comments, so I'll set it in the config file. 

config.toml <-- append the following to the [params] section
```
...
GithubId = "userid"
#GHrepo = "repo-permalink" #set blog repo if all issues will be associated to one repo. If issues will be associated to more than one repo, set the value in front matter 
+++
```

comments.html <-- update with githubid and github repo parameters
```
let url = "https://github.com/{{ .Site.Params.GithubId }}/{{ .Site.Params.GHrepo }}/issues/".concat(id);
let api_url = "https://api.github.com/repos/{{ .Site.Params.GithubId }}/{{ .Site.Params.GHrepo }}/issues/".concat(id, "/comments");
```

The ``GHissueID`` can stay in front matter since it is unique to a blog post. 

image

**Comment by lxndrblz** [comment]
@rkbright I'll give it a try and report back. Last night I couldn't get it instantly be working, but it might just be an error on my site.

**Comment by rkbright** [comment]
@lxndrblz - sounds good, also try with a current issue id, you should get the comment counter and link to github as shown in the image in the above thread.

**Comment by lxndrblz** [comment]
Hi @rkbright I finally got it working, it must have been a technical issue on my end. Thanks for all your efforts.

For comparison reason, I've also implemented a GitHub comments solution based on [Utteranc.es ](https://utteranc.es/), which is quite slick and much lower maintenance for me.  If you want to test it simple clone the `utterances` branch.
image

I am curious to hear what you think.

**Comment by rkbright** [comment]
Cool, I'll give it a look and will let you know my thoughts.

**Comment by rkbright** [comment]
I only had a few minutes tonight and could not get it to work, I'll try again tomorrow if I have more time. Based on the instructions listed on the homepage, and tinkering for a few minutes, it definitely looks pretty interesting and well supported compared the the script in my PR. I guess the major difference is where the github metadata is being defined - via a JS script (or maybe you could parameterize it) versus in front matter by adding the github issue id number. I also see they add in a link back - is that configurable?

**Comment by lxndrblz** [comment]
@rkbright  The setup procedure is really simple:

1. Install the app to your repo
2. Configure the parameters like this:
```yaml
[params.utterances]
repo = "lxndrblz/alexbilzcom-comments"
issueTerm = "pathname"
theme= "preferred-color-scheme"
# label =
```

The issues are generated and tracked automatically based on the the issueTerm, this paramter is very similar to your issue ID, with the difference that it automatically creates and updates the issues with various mappings. So you can create a mapping based on the title a path name but also a specific issue ID.

**Comment by rkbright** [comment]
I got it working, cool - comments can be created on the fly by readers. I think it's a good choice to integrate into your theme. One less thing you have to worry about in keeping your code up to date, compared to the code I provided. It's been great collaborating with you, Alexander! 

image

**Comment by lxndrblz** [comment]
@rkbright Thanks for testing and I hope you don't mind that we didn't use your solution this time. If in the future you have an idea, or another PR please let me know.

**Pull request closed without merging**
