### PR TITLE
feat: gitalk comment

### PR DESCRIPTION
**Pull request by mousemin**

### CODE REVIEW

**Comment by lxndrblz** [comment]
@mousemin Thanks for the PR. Would you mind adding a succinct description to the README, which explains how Gitalk can be configured?

**Comment by mousemin** [comment]
### Comments powered by Gitalk
No comment section is shown on the `single.html` unless a `repo` is specified in the `config.toml` file. If uncertain how parameter to configure, check out the official [documentation](https://github.com/gitalk/gitalk).

```toml
[params.gitalk]
clientID = "GitHub Application Client ID"
clientSecret = "GitHub Application Client Secret"
repo = "Repository name to store issues"
owner = "GitHub repo owner"
admin = "GitHub repo owner and collaborators, only these guys can initialize gitHub issues"
```

**Comment by mousemin** [comment]
> @mousemin Thanks for the PR. Would you mind adding a succinct description to the README, which explains how Gitalk can be configured?
### Comments powered by Gitalk
No comment section is shown on the `single.html` unless a `repo` is specified in the `config.toml` file. If uncertain how parameter to configure, check out the official [documentation](https://github.com/gitalk/gitalk).

```toml
[params.gitalk]
clientID = "GitHub Application Client ID"
clientSecret = "GitHub Application Client Secret"
repo = "Repository name to store issues"
owner = "GitHub repo owner"
admin = "GitHub repo owner and collaborators, only these guys can initialize gitHub issues"
```

**Review by lxndrblz — APPROVED** [review]
@mousemin LGTM.  Thanks for adding this feature to Anatole.

**Pull request merged**
