### PR TITLE
feat: Add option to display related posts

### PR DESCRIPTION
**Pull request by gummigroda**
## Description

New feature: **Display related posts after page content**

### Discussion
#283 Feature: Add related posts to footer of post

---

### Aditional Information (Optional)

- _Using built in Hugo functionality_
- _Possibly needs some css styling?_

---

### Checklist

Yes, I included all necessary artefacts, including:

- [ ] Tests
- [x] Documentation
- [x] Implementation (Code and Ressources)
- [x] Example (Screenshot)
image

---

### Testing Checklist

Yes, I ensured that all of the following scenarios were tested:

- [x] Desktop Light Mode (Default)
- [x] Desktop Dark Mode
- [ ] Desktop Light RTL Mode
- [ ] Desktop Dark RTL Mode
- [x] Mobile Light Mode
- [x] Mobile Dark Mode
- [ ] Mobile Light RTL Mode
- [ ] Mobile Dark RTL Mode

---

### CODE REVIEW

**Comment by lxndrblz** [comment]
@gummigroda Thanks for your PR for one of the outstanding feature requests!

I agree, a bit of styling might improve the appearance even further. Do you need help with the CSS or do you want to create it yourself and have me look over it?

One other thing that would be really cool is the ability to preview the post thumbnails. What do you think?

**Comment by gummigroda** [comment]
Hi,

Regarding the CSS, I don't really have any idea of what to do. If you or anyone else have the time, please style it as you think it fits.  
I totally agree with you, thumbnails would be awesome as seen on other websites and has been the inspiration to this PR. I'm just not sure how to do it as I believe it's tightly connected to the styling?

**Comment by lxndrblz** [comment]
@gummigroda Thanks for your response. I can take of the Styling. It might take a bit though, as I am currently quite busy porting all the CSS to SCSS. So please bare with me. :)

**Comment by lxndrblz** [comment]
@gummigroda Just want to let you know that I'll work on this one, as soon as I've merged #292.

**Comment by gummigroda** [comment]
@lxndrblz, No worries. 

Looked into the thumbnail possibility and found out that Hugo supports [image processing](https://gohugo.io/content-management/image-processing/). 
And as I understand it, to get the images of a related post they need to be in the same "Page Resources". I'm totally new to Hugo and this is a bit beyond me a.t.m.

**Review by lxndrblz — APPROVED** [review]
@gummigroda LGTM. Thanks for your PR.

**Comment by lxndrblz** [comment]
@gummigroda I wanted to inform you that I didn't go with the card style I had envisioned earlier as I could not find a viable way to make this work for sites that had both posts with a thumbnail and ones without. Furthermore, is the current approach more inline with the style of the series.

**Pull request merged**
