### PR TITLE
add feature readmore in index.html

### PR DESCRIPTION
**Pull request by xiangli2pro**
This adds '...Read more' link to each truncated post listed on Home Page.

### CODE REVIEW

**Comment by lxndrblz** [comment]
@xiangli2pro Thanks, I will make a few more tweaks to the code. That might take me a few days.

**Comment by lxndrblz** [comment]
@xiangli2pro Would you mind if we make the read more links optional? Personally I prefer the current minimalistic view, but I fully understand other opinions too. I think a read_more parameter could be a good compromise. What do you think?

**Comment by xiangli2pro** [comment]
@lxndrblz  Sure, I totally agree with the minimalistic view. My intention was to offer an option, not necessarily a fixed feature.
Thank you for asking.

**Comment by lxndrblz** [comment]
@xiangli2pro Okay, I agree there is a need for read more if the preview size is rather large. Hope to finish it tonight. Thanks again for bringing up the idea.

**Pull request merged**
