### PR TITLE
Language dropdown

### LINKED ISSUE #169: Better language dropdown
Right now the language menus in the navigation bar redirect the user to the main page of the website. Would it be possible to implement the language switcher as a dropdown instead so the user can switch between the different languages of a given page? Preferably, the language switch should redirect to the same page instead of redirecting back to the main page.

Sort of like the language switcher at the bottom of 1Password's website:
image

### PR DESCRIPTION
**Pull request by ericswpark**
Still a WIP

Tasks
- [x] Have the dropdown show up on click rather than on hover
- [x] Fix bug where dropdown triangle will show up before click on mobile only
        _Fixed, sort of - the JS sets the display attribute on page load to hide the triangle. Proper fix would be to fix it in CSS._
- [x] Move the language navbar item to the right of the navbar, instead of next to the navigational links on desktop. The language navbar item should be located on the left of the theme switcher button.
- [ ] Proper styling on mobile
  - [ ] Language switcher text is too big
  - [ ] The dropdown overlaps the language switcher button
- [ ] On clicking anywhere outside of the dropdown, the dropdown should be dismissed. There is some commented out code in the JS file that attempts to do this but it's broken and will cancel out with the code that toggles the dropdown in the first place, which results in no dropdown at all.
- [ ] Fix dropdown text color in dark mode (text is too grey)

Will close #169

### CODE REVIEW

**Comment by lxndrblz** [comment]
@ericswpark Thanks for the draft. I just gave it a try. Unfortunately, neither in mobile or desktop view the dropdown opens.
Did I miss something?

**Comment by ericswpark** [comment]
@lxndrblz that is weird! Did you pull from the `languagedropdown` branch from my repository?

Desktop:

https://user-images.githubusercontent.com/13326074/134336938-9023b90f-c180-4887-8a09-86175f9d0306.mov

Mobile:

https://user-images.githubusercontent.com/13326074/134337648-90aff0df-0433-4bb9-b049-c143e4649f69.mp4

**Comment by lxndrblz** [comment]
@ericswpark Yes, I had pulled the latest version from your branch, because I saw that you had commits there. 

In the meantime I had also worked on a purely CSS based version which works fairly way. By not relying on CSS it has the benefit that the menu would work, even if someone has JavaScript disabled in their browser:

https://user-images.githubusercontent.com/12200062/134369394-efa08cb2-d655-4a82-9524-bb529d65cd32.mp4

The only thing that is still missing is a proper mobile view.

**Comment by ericswpark** [comment]
> @ericswpark Yes, I had pulled the latest version from your branch, because I saw that you had commits there.

That is weird! Are there any errors in the console? I did have problems with the dropdown not opening, but only because of the buggy code that dismisses the dropdown on window click outside of the dropdown. That should be commented out though.

> In the meantime I had also worked on a purely CSS based version which works fairly way. By not relying on CSS it has the benefit that the menu would work, even if someone has JavaScript disabled in their browser:
> 2021-09-22.17-01-50.mp4
> 
> The only thing that is still missing is a proper mobile view.

This looks great, however I think the language controls should be next to the theme switcher to avoid confusion with navigational links. Not sure about the long language name but I guess that's easier to parse in one go instead of remembering language shortcodes. Maybe we can make it a configurable option?

If you push the changes to a separate branch I'll test it out here. Thank you for spending so much time on this!

**Comment by lxndrblz** [comment]
@ericswpark  No, unfortunately I could not find any errors in the script console. 

You can find the version from the video in the branch under:
https://github.com/lxndrblz/anatole/tree/languagedropdown

The name of the languages that are displayed in the dropdown is actually configured by the user. This allows a user to set a full name, a short code or even an emoji if they want.

I am still a bit torn about the placement of the language dropdown. I can see the merit of placing it separately from the menu items as this can aid as a visual distinction. For now, I want to finish the mobile view first.

**Comment by ericswpark** [comment]
Sounds good. I'll close this PR in favor of the CSS-only solution in the `languagedropdown` branch. We can continue tracking this issue in #169.

**Pull request closed without merging**
