### PR TITLE
Add size options to figure shortcode

### PR DESCRIPTION
**Pull request by alexanderdavide**
## Description

The figure shortcode is unflexible. Big images take up too much space (see a [blog post](https://blog.alex-eble.de/en/projects/air-support/)) of mine. This PR adds classes for users to adapt figure sizes to their needs.

---

### Checklist

Yes, I included all necessary artefacts, including:

- [ ] Tests
- [ ] Documentation (figure shortcode is not documented at all)
- [x] Implementation (Code and Ressources)
- [x] Example

---

### Testing Checklist

Yes, I ensured that all of the following scenarios were tested:

- [x] Desktop Light Mode (Default)
- [x] Desktop Dark Mode
- [x] Desktop Light RTL Mode
- [x] Desktop Dark RTL Mode
- [x] Mobile Light Mode
- [x] Mobile Dark Mode
- [x] Mobile Light RTL Mode
- [x] Mobile Dark RTL Mode

### CODE REVIEW

**Comment by lxndrblz** [comment]
@alexanderdavide I would name the class medium, small etc. as this would be consistent with the current definition "big". What do you think?

**Comment by alexanderdavide** [comment]
> @alexanderdavide I would name the class medium, small etc. as this would be consistent with the current definition "big". What do you think?

Can you please list your tiers replacing full, lg, md, sm? We need 4, Big and large should probably not be used together.

**Comment by lxndrblz** [comment]
I would go for big, medium, small, tiny.

**Comment by alexanderdavide** [comment]
> I would go for big, medium, small, tiny.

I've refactored it to have these classes. Actually, we could get rid of `big` as there is no difference between the style without classes. That's indeed something I found irritating in the [existing implementation](https://anatole-demo.netlify.app/post/figure-shortcode/).

**Comment by lxndrblz** [comment]
@alexanderdavide I was giving it some thought and concluded it might be best to reduce big to 90%.
What do you think?

**Comment by lxndrblz** [comment]
@alexanderdavide I was giving it some thought and concluded it might be best to reduce big to 90%.
What

**Comment by alexanderdavide** [comment]
> @alexanderdavide I was giving it some thought and concluded it might be best to reduce big to 90%. What do you think?

Good idea to have something in between 75 % and no class which potentially fills 100 %. How about meeting right in between at 87,5 %. This looks even better to my eyes.

**Pull request merged**
